// ORDER FORM
export const SUBMIT_FORM = 'SUBMIT_FORM'
export const FORM_SUBMITTING = 'FORM_SUBMITTING'
export const FORM_SUBMIT_SUCCESSFUL = 'FORM_SUBMIT_SUCCESSFUL'
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED'

// STATUSLOG

export const STATUSLOG_REQUEST = 'STATUSLOG_REQUEST'
export const STATUSLOG_FETCHING = 'STATUSLOG_FETCHING'
export const STATUSLOG_RECEIVED = 'STATUSLOG_RECEIVED'
export const STATUSLOG_REQUEST_FAILED = 'STATUSLOG_REQUEST_FAILED'

// ORDER
export const ORDER_REQUEST = 'ORDER_REQUEST'
export const ORDER_FETCHING = 'ORDER_FETCHING'
export const ORDER_RECEIVED = 'ORDER_RECEIVED'
export const ORDER_REQUEST_FAILED = 'ORDER_REQUEST_FAILED'
