export const SUBMIT_FORM = 'SUBMIT_FORM'
export const FORM_SUBMITTING = 'FORM_SUBMITTING'
export const FORM_SUBMIT_SUCCESSFUL = 'FORM_SUBMIT_SUCCESSFUL'
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED'