// USER

export const USER_SESSION_REQUEST = 'USER_SESSION_REQUEST'
export const USER_SESSION_FETCHING = 'USER_SESSION_FETCHING'
export const USER_SESSION_RECEIVED = 'USER_SESSION_RECEIVED'
export const USER_SESSION_REQUEST_FAILED = 'USER_SESSION_REQUEST_FAILED'

// INITALIZE APP

export const INITIALIZE_APPLICATION = 'INITIALIZE_APPLICATION'
export const APPLICATION_READY = 'APPLICATION_READY'


// ORDER
export const SUBMIT_FORM = 'SUBMIT_FORM'
export const FORM_SUBMITTING = 'FORM_SUBMITTING'
export const FORM_SUBMIT_SUCCESSFUL = 'FORM_SUBMIT_SUCCESSFUL'
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED'
