// SESSION

export const USER_SESSION_POLLING_START = 'USER_SESSION_POLLING_START'
export const USER_SESSION_POLLING = 'USER_SESSION_FETCHING'
export const USER_SESSION_ACTIVE = 'USER_SESSION_ACTIVE'
export const USER_SESSION_EXPIRED = 'USER_SESSION_EXPIRED'
export const USER_SESSION_POLLING_STOP = 'USER_SESSION_POLLING_STOP'

// USER

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_FETCHING = 'USER_PROFILE_FETCHING'
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED'
export const USER_PROFILE_REQUEST_FAILED = 'USER_PROFILE_REQUEST_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'

// INITALIZE APP

export const INITIALIZE_APPLICATION = 'INITIALIZE_APPLICATION'
export const APPLICATION_READY = 'APPLICATION_READY'

// POLLING

export const POLL_SESSION_START = 'POLL_SESSION_START'
export const POLL_SESSION_STOP = 'POLL_SESSION_STOP'

// ORDERFORM DATA
export const ENVIRONMENTS_REQUEST = 'ENVIRONMENTS_REQUEST'
export const ENVIRONMENTS_FETCHING = 'ENVIRONMENTS_FETCHING'
export const ENVIRONMENTS_RECEIVED = 'ENVIRONMENTS_RECEIVED'
export const ENVIRONMENTS_REQUEST_FAILED = 'ENVIRONMENTS_REQUEST_FAILED'
